//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K12.Retake.Shinmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K12.Retake.Shinmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap barchart_64 {
            get {
                object obj = ResourceManager.GetObject("barchart_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brand_write_64 {
            get {
                object obj = ResourceManager.GetObject("brand_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap desk_64 {
            get {
                object obj = ResourceManager.GetObject("desk_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lesson_planning_clock_64 {
            get {
                object obj = ResourceManager.GetObject("lesson_planning_clock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap marker_fav_64 {
            get {
                object obj = ResourceManager.GetObject("marker_fav_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;重補修課程資料&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;組合鍵值&quot;&gt;
        ///            &lt;Field Name=&quot;課程名稱&quot; /&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field Name=&quot;梯次&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;課程名稱&quot; Description=&quot;課程名稱&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetakeCourse {
            get {
                return ResourceManager.GetString("RetakeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;重補修學生修課&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;組合鍵值&quot;&gt;
        ///            &lt;Field Name=&quot;課程名稱&quot; /&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field Name=&quot;梯次&quot; /&gt;
        ///	    &lt;Field Name=&quot;學號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///
        ///
        ///  &lt;Field Required=&quot;True&quot; Name=&quot;課程名稱&quot; Description=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetakeSCAttend {
            get {
                return ResourceManager.GetString("RetakeSCAttend", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap subject_del {
            get {
                object obj = ResourceManager.GetObject("subject_del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap time_frame_refresh_128 {
            get {
                object obj = ResourceManager.GetObject("time_frame_refresh_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 刪除課程 {
            get {
                object obj = ResourceManager.GetObject("刪除課程", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 匯出 {
            get {
                object obj = ResourceManager.GetObject("匯出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] 及格人數樣板 {
            get {
                object obj = ResourceManager.GetObject("及格人數樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 學生選課清單 {
            get {
                object obj = ResourceManager.GetObject("學生選課清單", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 學生重補修缺曠通知單扣考範本 {
            get {
                object obj = ResourceManager.GetObject("學生重補修缺曠通知單扣考範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 學生重補修缺曠通知單範本 {
            get {
                object obj = ResourceManager.GetObject("學生重補修缺曠通知單範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 建議重補修名單_filter_data_add_64 {
            get {
                object obj = ResourceManager.GetObject("建議重補修名單_filter_data_add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 新增課程 {
            get {
                object obj = ResourceManager.GetObject("新增課程", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] 缺曠通知單學生名單範本 {
            get {
                object obj = ResourceManager.GetObject("缺曠通知單學生名單範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 缺曠通知單範本 {
            get {
                object obj = ResourceManager.GetObject("缺曠通知單範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 課程缺曠名單樣板 {
            get {
                object obj = ResourceManager.GetObject("課程缺曠名單樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 課程點名單樣板 {
            get {
                object obj = ResourceManager.GetObject("課程點名單樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 重補修科目管理_project_64 {
            get {
                object obj = ResourceManager.GetObject("重補修科目管理_project_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] 重補修課程缺曠樣板 {
            get {
                object obj = ResourceManager.GetObject("重補修課程缺曠樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 重補修課表管理_schedule_write_64 {
            get {
                object obj = ResourceManager.GetObject("重補修課表管理_schedule_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 開課 {
            get {
                object obj = ResourceManager.GetObject("開課", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
